### ISSUE TITLE
Highest not outright crazy resolution with 64 colours

### ISSUE THREAD

**Issue by leighbb** [julianregel/agonprograms#1]
I have been experimenting and the highest resolution I have found that supports 64 colours is....416x312

Where does this crazy number come from? It is actually half (in both dimensions) of 832x624...which is an MAC resolution my monitor supports officially. Both are working well for me. Here are the modeline definitions if you want to give them a go...

    #define VGA_416x312_75Hz "\"416x312@75Hz\" 28.64   416 432 464 576 312 312 314 333 -HSync -VSync DoubleScan"
    #define VGA_832x624_75Hz "\"832x624@75Hz\" 57.28   832 864 928 1152 624 625 628 667 -HSync -VSync"

    errVal = change_resolution(64, VGA_416x312_75Hz);
    errVal = change_resolution(4, VGA_832x624_75Hz);

I attach my monitor documentation for the modes it supports:
![image](https://github.com/julianregel/agonprograms/assets/5477785/d6ea14c5-32e6-4985-a6b4-72cff2880eb6)

**Comment by julianregel** [comment]
Hello @leighbb.

Sorry for not responding. I didn't pick up a notification there was an issue and I'm still new to GitHub :-)

I submitted a pull request to Dean that (at this point) intentionally only includes the "standard" VGA and most common SVGA modes that the Agon supports. The rationale is to get a base line established that should work for everyone.

There are some modes that could be added at a later date, but these are likely to be more niche and work with fewer monitors. If I get to add those, I'll look to include yours too. Thanks.
